### ISSUE TITLE
Bug in the main file

### ISSUE THREAD

**Issue by bicisteadm** [onlime/sendmail-wrapper#3]
I wanted to use this project for my modest webserver but it did not work. When I send an email from php so email delivered but the limitation does not work, I tried to command in cmd,, php / usr / sbin / sendmail-wrapper "and announced that the following error,, PHP Notice: Use of undefined constant self - assumed 'self 'in /opt/sendmail-wrapper/app/ConfigLoader.php on line 83 ". How do I fix this so that my work?
Thanks.

**Comment by onlime** [comment]
weird, Github has translated your comment to Czech. :)
It should be fixed in cc41aca5a3538fa895752d55b7e7ca3b26046f1e
Cheers.
