### ISSUE TITLE
Limitation does not work

### ISSUE THREAD

**Issue by bicisteadm** [onlime/sendmail-wrapper#4]
Hello,
in /etc/cgi/php.ini I set sendmail_path,, = / usr / sbin / sendmail-wrapper "but the script does not work. I have a database of settings and connections, but nothing in it does not write too limiting and does not work. Is there a debug mode where I could find out what is wrong? Thanks.

**Comment by onlime** [comment]
Is there possibly no `/usr/bin/php` on your system?
I made the scripts a bit more portable by replacing the php shebang line with `/usr/bin/env php` in c36da020dbb0190c945060212cac16675afb9843
Please try again.

**Comment by bicisteadm** [comment]
Unfortunately, it still does not work. My system is Debian Jessie. I have php5 and apache2 and postfix.
